name: GitHub Actions Self Hosted Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - main

jobs:
  Explore-Self-Hosted-Actions:
    runs-on: [self-hosted, linux, x64, desktop]
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by You!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: rm -r /home/chamikara/my-apps/github/portfolio
      - run: cp -r ${{ github.workspace }} /home/chamikara/my-apps/github
      - run: cd /home/chamikara/my-apps/github/portfolio
      - run: npm ci
      - run: npm run build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
